language: python
python:
    - "3.6"
    - "3.6-dev"
    - "nightly"

install:
    - pip install pipenv
    - pipenv install --dev

script:
    #- pipenv run pytest --flake8
    - pipenv run python manage.py test
